<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto

namespace Grpc\Health\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.health.v1.HealthCheckResponse</code>
 */
class HealthCheckResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1;</code>
     */
    private $status = 0;

    public function __construct() {
        \GPBMetadata\Health::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.grpc.health.v1.HealthCheckResponse.ServingStatus status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Grpc\Health\V1\HealthCheckResponse_ServingStatus::class);
        $this->status = $var;

        return $this;
    }

}

