<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto

namespace swoole\grpc\Grpc\Health\V1;

/**
 * Protobuf enum <code>Grpc\Health\V1\HealthCheckResponse\ServingStatus</code>
 */
class HealthCheckResponse_ServingStatus
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>SERVING = 1;</code>
     */
    const SERVING = 1;
    /**
     * Generated from protobuf enum <code>NOT_SERVING = 2;</code>
     */
    const NOT_SERVING = 2;
}

